const dc = [
  {
    id: 1,
    title: "Classical Grooves",
    description: "Immerse yourself in the world of Bollywood dance, combining traditional and modern moves.",
    instructor: "Priya Patel",
    prices: "Rs. 1500",
    imageUrl: "d4.jpg",
  },
  {
    id: 2,
    title: "Kathak Expressions",
    description: "Learn the intricate footwork and storytelling aspects of the classical Kathak dance.",
    instructor: "Rajesh Sharma",
    prices: "Rs. 1800",
    imageUrl: "d2.jpg",
  },
  {
    id: 3,
    title: "Folk Fusion Fiesta",
    description: "Explore the diversity of Indian folk dances, blending various regional styles.",
    instructor: "Anjali Desai",
    prices: "Rs. 1200",
    imageUrl: "d7.jpg",
  },
  {
    id: 4,
    title: "Contemporary Bharatanatyam",
    description: "Infuse contemporary elements into the classical Bharatanatyam dance form.",
    instructor: "Amit Khanna",
    prices: "Rs. 1600",
    imageUrl: "d4.jpg",
  },
  {
    id: 5,
    title: "Funky Fusion Moves",
    description: "Master urban and hip-hop dance styles with an Indian twist.",
    instructor: "Neha Rao",
    prices: "Rs. 1400",
    imageUrl: "d2.jpg",
  },
  {
    id: 6,
    title: "Garba Delight",
    description: "Learn the vibrant and joyful Gujarati Garba dance, perfect for celebrations.",
    instructor: "Rahul Mehta",
    prices: "Rs. 1100",
    imageUrl: "d2.jpg",
  },
  {
    id: 7,
    title: "Odissi Grace",
    description: "Discover the grace and beauty of the classical Odissi dance from the eastern regions of India.",
    instructor: "Lakshmi Das",
    prices: "Rs. 1700",
    imageUrl: "d7.jpg",
  },
  {
    id: 8,
    title: "Fusion Folk Jive",
    description: "Blend traditional folk dances with modern jive, creating a unique dance experience.",
    instructor: "Vikram Singh",
    prices: "Rs. 1900",
    imageUrl: "d7.jpg",
  },
  {
    id: 9,
    title: "Punjabi Bhangra Beats",
    description: "Get your energy flowing with the lively and upbeat Punjabi Bhangra dance.",
    instructor: "Harpreet Kaur",
    prices: "Rs. 1300",
    imageUrl: "d9.jpg",
  },
  {
    id: 10,
    title: "Rajasthani Kalbelia",
    description: "Explore the unique twirls and spins of the Rajasthani Kalbelia dance.",
    instructor: "Arun Sharma",
    prices: "Rs. 1500",
    imageUrl: "d10.jpg",
  },
];

export default dc ; 
